import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1773938616580 implements MigrationInterface {
    name = 'Init1773938616580'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "attendance_month_settings" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" bigint NOT NULL, "month" integer NOT NULL, "year" integer NOT NULL, "standard_workdays" numeric(6,2) NOT NULL, "closing_date" date, CONSTRAINT "PK_514c83b51ccc3772faa205da219" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b065ef630ddc3e104f35f6c370" ON "attendance_month_settings" ("company_id", "month", "year") `);
        await queryRunner.query(`CREATE TABLE "shift_rest_rules" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "shift_id" bigint NOT NULL, "rest_begin_time" TIME, "rest_end_time" TIME, CONSTRAINT "PK_0ce970140559470ef7f84a69713" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_156e6b1044f24a6c9192f9e93a" ON "shift_rest_rules" ("shift_id", "rest_begin_time", "rest_end_time") `);
        await queryRunner.query(`CREATE TABLE "shifts" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" bigint NOT NULL, "code" character varying(50) NOT NULL, "shift_name" character varying NOT NULL, "start_time" TIMESTAMP WITH TIME ZONE NOT NULL, "end_time" TIMESTAMP WITH TIME ZONE NOT NULL, "allow_late_minutes" integer NOT NULL DEFAULT '0', "allow_early_minutes" integer NOT NULL DEFAULT '0', "shift_hours" double precision NOT NULL DEFAULT '8', CONSTRAINT "PK_84d692e367e4d6cdf045828768c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a29e2a5f47594e13dec61b1deb" ON "shifts" ("company_id", "code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_555c88b66687c3694b196c5b02" ON "shifts" ("company_id", "shift_name") `);
        await queryRunner.query(`CREATE TABLE "attendance_groups" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" bigint NOT NULL, "code" character varying(50) NOT NULL, "group_name" character varying NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'ACTIVE', "default_shift_id" bigint, CONSTRAINT "PK_7240eb99fe29f6093e1cc6550e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e61dd1fab443e84f7576c7f2fa" ON "attendance_groups" ("company_id", "code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_912027997643770c7363e28df9" ON "attendance_groups" ("company_id", "group_name") `);
        await queryRunner.query(`CREATE TABLE "job_levels" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" bigint NOT NULL, "code" character varying(50) NOT NULL, "level_name" character varying NOT NULL, "status" character varying(20) NOT NULL DEFAULT 'ACTIVE', CONSTRAINT "PK_86a4e88cf87968ed4bfc349eaa3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_ff4edf9c32127346169a68fcd9" ON "job_levels" ("company_id", "code") `);
        await queryRunner.query(`CREATE TABLE "employee_types" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" bigint NOT NULL, "code" character varying(50) NOT NULL, "type_name" character varying NOT NULL, CONSTRAINT "PK_bfdd4577957b57ec973469ede78" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4c2afe0e63d665bfb42e7c47e2" ON "employee_types" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c39e1b9bddd039527213a68eb4" ON "employee_types" ("company_id", "code") `);
        await queryRunner.query(`CREATE TABLE "employee_statuses" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" bigint NOT NULL, "code" character varying(50) NOT NULL, "status_name" character varying NOT NULL, CONSTRAINT "PK_002adb1bf8f8e84e808e753e450" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b69943ca196ae982e02fa5ef98" ON "employee_statuses" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6cfec6890bce2fe8dfb9c08266" ON "employee_statuses" ("company_id", "status_name") `);
        await queryRunner.query(`CREATE TABLE "attendance_methods" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" bigint NOT NULL, "code" character varying(50) NOT NULL, "method_name" character varying NOT NULL, CONSTRAINT "PK_af7e2e948e2db133b7bf272bb08" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f7ab5fa6781fcf098de4a62e48" ON "attendance_methods" ("company_id", "method_name") `);
        await queryRunner.query(`CREATE TABLE "leave_types" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" bigint NOT NULL, "code" character varying(50) NOT NULL, "leave_type_name" character varying NOT NULL, "is_deduct_leave" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_359223e0755d19711813cd07394" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_600530eb1d9f853dd746e5819c" ON "leave_types" ("code") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_df83f49dd79df2a2c3f189fd8f" ON "leave_types" ("company_id", "leave_type_name") `);
        await queryRunner.query(`CREATE TABLE "leave_policy_rules" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "policy_id" bigint NOT NULL, "leave_type_id" bigint NOT NULL, "quota_days" numeric(6,2), "is_deduct_leave" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_970f8678887600cf41f25b5d8f1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c58a23a2bf708464e268ca2415" ON "leave_policy_rules" ("policy_id", "leave_type_id") `);
        await queryRunner.query(`CREATE TABLE "leave_policies" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" bigint NOT NULL, "policy_name" character varying NOT NULL, "standard_workdays_in_policy" numeric(6,2), CONSTRAINT "PK_7d3b46bd2974cbb56e3831f3f34" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_89303fbcb2f5897d84f1ccec35" ON "leave_policies" ("company_id", "policy_name") `);
        await queryRunner.query(`CREATE TABLE "attendance_daily_punches" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "daily_timesheet_id" bigint, "punch_index" integer NOT NULL, "check_in_time" TIMESTAMP, "check_out_time" TIMESTAMP, "check_in_result" character varying, "check_out_result" character varying, "late_hours" numeric(6,2) NOT NULL DEFAULT '0', "early_hours" numeric(6,2) NOT NULL DEFAULT '0', "miss_check_in" boolean NOT NULL DEFAULT false, "miss_check_out" boolean NOT NULL DEFAULT false, "check_in_actual" TIMESTAMP, "check_out_actual" TIMESTAMP, CONSTRAINT "PK_a8cb073de2ce290c5a0cda45f7c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e7ca3649028e5eab9ca4ea5ea3" ON "attendance_daily_punches" ("daily_timesheet_id", "punch_index") `);
        await queryRunner.query(`CREATE TABLE "request_detail_time_off" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "attendance_request_id" bigint NOT NULL, "leave_type_id" bigint, "leave_type_details" character varying, "start_time" TIMESTAMP NOT NULL, "end_time" TIMESTAMP NOT NULL, "hours" double precision NOT NULL, CONSTRAINT "REL_4cca4871b1f37d46e6c9067186" UNIQUE ("attendance_request_id"), CONSTRAINT "PK_beec7393efe671cc03d1259c2f0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "request_detail_overtime" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "attendance_request_id" bigint NOT NULL, "start_time" TIMESTAMP NOT NULL, "end_time" TIMESTAMP NOT NULL, "convert_type" character varying, "ot_rule_id" integer NOT NULL, "ratio_convert" double precision NOT NULL DEFAULT '1', "hours_ratio" double precision NOT NULL, CONSTRAINT "REL_bc21d1820c0393e0d6b9fde485" UNIQUE ("attendance_request_id"), CONSTRAINT "PK_0f9fe90bd09885edf2408270c99" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "request_detail_adjustment" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "attendance_request_id" bigint NOT NULL, "original_record" TIMESTAMP, "replenishment_time" TIMESTAMP, "maternity_shift" character varying, "maternity_start_date" date, "maternity_end_date" date, "employee_id_swap" character varying, "date_original_shift" date, "date_swap_shift" date, CONSTRAINT "REL_8bf917615012117d7f04fd4cf9" UNIQUE ("attendance_request_id"), CONSTRAINT "PK_eb5985193f0add2622e82c04475" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attendance_requests" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "request_id" character varying NOT NULL, "employee_id" character varying NOT NULL, "note" character varying, "status" character varying NOT NULL, "applied_date" date NOT NULL, "is_counted" boolean NOT NULL DEFAULT true, "total_hours" double precision, "leave_type_id" bigint, "type" "public"."attendance_requests_type_enum" NOT NULL, "company_id" bigint NOT NULL, "record_id" character varying, "raw_data" jsonb, "daily_timesheet_id" bigint, CONSTRAINT "UQ_d2075e3a8a3cc4c8dd5b366a4f2" UNIQUE ("record_id"), CONSTRAINT "PK_675d1d22d15749d3048809f0941" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "attendance_daily_timesheets" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" bigint NOT NULL, "employee_id" bigint NOT NULL, "attendance_date" date NOT NULL, "weekday" integer NOT NULL, "month" integer NOT NULL, "year" integer NOT NULL, "shift_id" character varying, "check_in_raw" TIMESTAMP, "check_out_raw" TIMESTAMP, "check_in_actual" TIMESTAMP, "check_out_actual" TIMESTAMP, "check_in_result" character varying, "check_out_result" character varying, "late_minutes" integer NOT NULL DEFAULT '0', "early_leave_minutes" integer NOT NULL DEFAULT '0', "rest_minutes" integer NOT NULL DEFAULT '0', "work_minutes" integer NOT NULL DEFAULT '0', "actual_work_hours" numeric(6,2) NOT NULL DEFAULT '0', "total_work_hours_standard" numeric(6,2) NOT NULL DEFAULT '0', "missing_check_in" boolean NOT NULL DEFAULT false, "missing_check_out" boolean NOT NULL DEFAULT false, "is_late" boolean NOT NULL DEFAULT false, "is_early_leave" boolean NOT NULL DEFAULT false, "is_leave" boolean NOT NULL DEFAULT false, "leave_hours" numeric(6,2) NOT NULL DEFAULT '0', "is_remote" boolean NOT NULL DEFAULT false, "remote_hours" numeric(6,2) NOT NULL DEFAULT '0', "is_ot" boolean NOT NULL DEFAULT false, "ot_hours" numeric(6,2) NOT NULL DEFAULT '0', "is_holiday" boolean NOT NULL DEFAULT false, "is_redundant" boolean NOT NULL DEFAULT false, "work_hours_redundant" double precision NOT NULL DEFAULT '0', "adjustment_hours" numeric(6,2) NOT NULL DEFAULT '0', "attendance_status" character varying NOT NULL DEFAULT 'Lack', "actual_workday" numeric(4,2) NOT NULL DEFAULT '0', "calculation_version" character varying, "calculated_at" TIMESTAMP, "is_recalculated" boolean NOT NULL DEFAULT false, "is_configured_off_day" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_4446090bbfdd6f87c70d5242242" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_91c8bfaa321bf2003b5d6856bf" ON "attendance_daily_timesheets" ("employee_id", "attendance_date") `);
        await queryRunner.query(`CREATE TABLE "attendance_punch_records" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" bigint NOT NULL, "employee_id" bigint NOT NULL, "daily_timesheet_id" bigint, "lark_record_id" character varying NOT NULL, "punch_time" TIMESTAMP NOT NULL, "punch_type" character varying, "punch_result" character varying, "source_type" character varying, "latitude" numeric(10,7), "longitude" numeric(10,7), "address" character varying, "device_id" character varying, "ssid" character varying, "photo_url" text, "shift_time_target" TIMESTAMP, "raw_payload" jsonb, CONSTRAINT "PK_b17cbce2630924639a4852b032e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f52963827865bbefb1398e754f" ON "attendance_punch_records" ("lark_record_id") `);
        await queryRunner.query(`CREATE TABLE "departments" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" bigint NOT NULL, "department_name" character varying NOT NULL, "department_code" character varying, "parent_id" bigint, "status" character varying(20) NOT NULL DEFAULT 'ACTIVE', CONSTRAINT "PK_839517a681a86bb84cbcc6a1e9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_bb9081146343629a3a34ecd1f4" ON "departments" ("company_id", "department_name") `);
        await queryRunner.query(`CREATE TABLE "employees" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" bigint NOT NULL, "work_location_id" bigint NOT NULL, "user_id" character varying NOT NULL, "user_name" character varying NOT NULL, "full_name" character varying NOT NULL, "lark_id" character varying, "email" character varying, "phone_number" character varying, "manager_id" bigint, "standard_workdays" numeric(6,2), "birthday" date, "gender" character varying(10), "joined_at" date, "resigned_at" date, "is_saturday_off" boolean NOT NULL DEFAULT false, "is_angel" boolean NOT NULL DEFAULT false, "attendance_group_id" bigint, "job_level_id" bigint, "employee_type_id" bigint, "employee_status_id" bigint, "attendance_method_id" bigint, "leave_policy_id" bigint, CONSTRAINT "PK_b9535a98350d5b26e7eb0c26af4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bcdf921072a19dd2758a628c5c" ON "employees" ("manager_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ed8bf314ae9f18006123e23566" ON "employees" ("company_id", "email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a123f781aec89de6ee8ea17246" ON "employees" ("company_id", "lark_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c689b7c9078088568fe841f3a4" ON "employees" ("company_id", "user_id") `);
        await queryRunner.query(`CREATE TABLE "attendance_monthly_timesheets" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" bigint NOT NULL, "employee_id" bigint NOT NULL, "month" integer NOT NULL, "year" integer NOT NULL, "total_work_days" numeric(10,3) NOT NULL DEFAULT '0', "total_paid_days" numeric(10,3) NOT NULL DEFAULT '0', "total_work_hours" numeric(10,2) NOT NULL DEFAULT '0', "total_late_days" integer NOT NULL DEFAULT '0', "total_late_minutes" integer NOT NULL DEFAULT '0', "total_early_leave_minutes" integer NOT NULL DEFAULT '0', "total_missing_check" integer NOT NULL DEFAULT '0', "total_ot_hours" numeric(10,2) NOT NULL DEFAULT '0', "total_leave_days" numeric(10,3) NOT NULL DEFAULT '0', "total_remote_days" numeric(10,3) NOT NULL DEFAULT '0', "confirmation_status" character varying NOT NULL DEFAULT 'pending', "last_sync_at" TIMESTAMP, CONSTRAINT "PK_38d591168ea59bcd8a0fbaf84c1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_92e489091fca8e3433a1f6042b" ON "attendance_monthly_timesheets" ("employee_id", "company_id", "month", "year") `);
        await queryRunner.query(`CREATE TABLE "companies" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_name" character varying NOT NULL, CONSTRAINT "PK_d4bc3e82a314fa9e29f652c2c22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "work_locations" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" bigint NOT NULL, "location_name" character varying NOT NULL, "address" text, "latitude" numeric(10,8), "longitude" numeric(11,8), "radius_meters" integer NOT NULL DEFAULT '200', CONSTRAINT "PK_b6821db96b6c51d12b6561a79aa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_edc5d3a356155c2fec8a3e5e33" ON "work_locations" ("company_id", "location_name") `);
        await queryRunner.query(`CREATE TABLE "timesheet_adjustment_types" ("id" BIGSERIAL NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "company_id" bigint NOT NULL, "adjustment_type_name" character varying NOT NULL, CONSTRAINT "PK_7807e04ac527a193077bf03cba2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_641ddaa8aaa61c0a3bd554e3d7" ON "timesheet_adjustment_types" ("company_id", "adjustment_type_name") `);
        await queryRunner.query(`CREATE TABLE "employee_departments" ("employee_id" bigint NOT NULL, "department_id" bigint NOT NULL, CONSTRAINT "PK_39a9f76731958d79dbb9b706cae" PRIMARY KEY ("employee_id", "department_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ed390b2466f6f70591a7d93e0a" ON "employee_departments" ("employee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b42531bfb853f20d06f1177653" ON "employee_departments" ("department_id") `);
        await queryRunner.query(`ALTER TABLE "attendance_month_settings" ADD CONSTRAINT "FK_9c7dbd7a2b677fd4bccaf6e0dad" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shift_rest_rules" ADD CONSTRAINT "FK_2fed9c0812c54848b2cd7201c2e" FOREIGN KEY ("shift_id") REFERENCES "shifts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shifts" ADD CONSTRAINT "FK_e155f8dd2a50f91604c8d946369" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_groups" ADD CONSTRAINT "FK_496072134ffffe2a4bcc6fb1d9d" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_groups" ADD CONSTRAINT "FK_1bdd8eb6d4a4964b55e959f3581" FOREIGN KEY ("default_shift_id") REFERENCES "shifts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "job_levels" ADD CONSTRAINT "FK_eafba85d3dac4465dfb623edcc0" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_types" ADD CONSTRAINT "FK_aac82752e7927d632704a21e61b" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_statuses" ADD CONSTRAINT "FK_a6574c554b6e0b7493570e464d2" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_methods" ADD CONSTRAINT "FK_7cf15dacc1770dcc50c9bf2a7d2" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_types" ADD CONSTRAINT "FK_dd27cdf2939bc23d54c5a76ffee" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_policy_rules" ADD CONSTRAINT "FK_192cb2e4093ad9d4e9c4582dc4b" FOREIGN KEY ("policy_id") REFERENCES "leave_policies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_policy_rules" ADD CONSTRAINT "FK_3b14a2e187e55b94c01d54223f6" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leave_policies" ADD CONSTRAINT "FK_e944bd0d894099fe5632364d219" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_daily_punches" ADD CONSTRAINT "FK_d2268f587719729593e28fc6936" FOREIGN KEY ("daily_timesheet_id") REFERENCES "attendance_daily_timesheets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request_detail_time_off" ADD CONSTRAINT "FK_4cca4871b1f37d46e6c90671864" FOREIGN KEY ("attendance_request_id") REFERENCES "attendance_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request_detail_overtime" ADD CONSTRAINT "FK_bc21d1820c0393e0d6b9fde485d" FOREIGN KEY ("attendance_request_id") REFERENCES "attendance_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "request_detail_adjustment" ADD CONSTRAINT "FK_8bf917615012117d7f04fd4cf9d" FOREIGN KEY ("attendance_request_id") REFERENCES "attendance_requests"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_requests" ADD CONSTRAINT "FK_f3f81867fa1bc0c9779810e33ea" FOREIGN KEY ("leave_type_id") REFERENCES "leave_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_requests" ADD CONSTRAINT "FK_af3864deb195ef249e45de7fbcc" FOREIGN KEY ("daily_timesheet_id") REFERENCES "attendance_daily_timesheets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_requests" ADD CONSTRAINT "FK_06a299c0ffc4cbe9b9f94499407" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_daily_timesheets" ADD CONSTRAINT "FK_dd65462536c8766b20f1a2959ce" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_daily_timesheets" ADD CONSTRAINT "FK_b62ec386489f03107f0e0d4c6bf" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_punch_records" ADD CONSTRAINT "FK_c772b416752de70012f5be0aabd" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_punch_records" ADD CONSTRAINT "FK_d0057f6b04224b88d7d6ab6ae77" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_punch_records" ADD CONSTRAINT "FK_df86dd872a98b3d2e84e6058821" FOREIGN KEY ("daily_timesheet_id") REFERENCES "attendance_daily_timesheets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_541e3d07c93baa9cc42b149a5fb" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "departments" ADD CONSTRAINT "FK_700b0b13f494cb37b6ca929e79b" FOREIGN KEY ("parent_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_bcdf921072a19dd2758a628c5c0" FOREIGN KEY ("manager_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_c5a7de0798cd028ba681bdcaf02" FOREIGN KEY ("attendance_group_id") REFERENCES "attendance_groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_b1507ca50d9d279f752ceffc1c7" FOREIGN KEY ("job_level_id") REFERENCES "job_levels"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_10586415772b6235abf83c445e3" FOREIGN KEY ("employee_type_id") REFERENCES "employee_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_d648b02390d7ce76ace5da627ff" FOREIGN KEY ("employee_status_id") REFERENCES "employee_statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_caf9cd06ec683f5f1d65535f8df" FOREIGN KEY ("attendance_method_id") REFERENCES "attendance_methods"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_0dcd192a411cb97df0e1e0b35d8" FOREIGN KEY ("leave_policy_id") REFERENCES "leave_policies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_7f3eeef59eece4147effe7bfa6a" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employees" ADD CONSTRAINT "FK_d7dc7ee3bdb6fed2d2c95a59a4f" FOREIGN KEY ("work_location_id") REFERENCES "work_locations"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_monthly_timesheets" ADD CONSTRAINT "FK_7361861ffeb535b290c7bb3a2ef" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "attendance_monthly_timesheets" ADD CONSTRAINT "FK_cc98cc136f67d5039838708c1bc" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "work_locations" ADD CONSTRAINT "FK_84bd9755bd49e0191fd8fad91c5" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheet_adjustment_types" ADD CONSTRAINT "FK_3199e582053049eae2c6808c99b" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "employee_departments" ADD CONSTRAINT "FK_ed390b2466f6f70591a7d93e0a1" FOREIGN KEY ("employee_id") REFERENCES "employees"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "employee_departments" ADD CONSTRAINT "FK_b42531bfb853f20d06f11776535" FOREIGN KEY ("department_id") REFERENCES "departments"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "employee_departments" DROP CONSTRAINT "FK_b42531bfb853f20d06f11776535"`);
        await queryRunner.query(`ALTER TABLE "employee_departments" DROP CONSTRAINT "FK_ed390b2466f6f70591a7d93e0a1"`);
        await queryRunner.query(`ALTER TABLE "timesheet_adjustment_types" DROP CONSTRAINT "FK_3199e582053049eae2c6808c99b"`);
        await queryRunner.query(`ALTER TABLE "work_locations" DROP CONSTRAINT "FK_84bd9755bd49e0191fd8fad91c5"`);
        await queryRunner.query(`ALTER TABLE "attendance_monthly_timesheets" DROP CONSTRAINT "FK_cc98cc136f67d5039838708c1bc"`);
        await queryRunner.query(`ALTER TABLE "attendance_monthly_timesheets" DROP CONSTRAINT "FK_7361861ffeb535b290c7bb3a2ef"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_d7dc7ee3bdb6fed2d2c95a59a4f"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_7f3eeef59eece4147effe7bfa6a"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_0dcd192a411cb97df0e1e0b35d8"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_caf9cd06ec683f5f1d65535f8df"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_d648b02390d7ce76ace5da627ff"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_10586415772b6235abf83c445e3"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_b1507ca50d9d279f752ceffc1c7"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_c5a7de0798cd028ba681bdcaf02"`);
        await queryRunner.query(`ALTER TABLE "employees" DROP CONSTRAINT "FK_bcdf921072a19dd2758a628c5c0"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_700b0b13f494cb37b6ca929e79b"`);
        await queryRunner.query(`ALTER TABLE "departments" DROP CONSTRAINT "FK_541e3d07c93baa9cc42b149a5fb"`);
        await queryRunner.query(`ALTER TABLE "attendance_punch_records" DROP CONSTRAINT "FK_df86dd872a98b3d2e84e6058821"`);
        await queryRunner.query(`ALTER TABLE "attendance_punch_records" DROP CONSTRAINT "FK_d0057f6b04224b88d7d6ab6ae77"`);
        await queryRunner.query(`ALTER TABLE "attendance_punch_records" DROP CONSTRAINT "FK_c772b416752de70012f5be0aabd"`);
        await queryRunner.query(`ALTER TABLE "attendance_daily_timesheets" DROP CONSTRAINT "FK_b62ec386489f03107f0e0d4c6bf"`);
        await queryRunner.query(`ALTER TABLE "attendance_daily_timesheets" DROP CONSTRAINT "FK_dd65462536c8766b20f1a2959ce"`);
        await queryRunner.query(`ALTER TABLE "attendance_requests" DROP CONSTRAINT "FK_06a299c0ffc4cbe9b9f94499407"`);
        await queryRunner.query(`ALTER TABLE "attendance_requests" DROP CONSTRAINT "FK_af3864deb195ef249e45de7fbcc"`);
        await queryRunner.query(`ALTER TABLE "attendance_requests" DROP CONSTRAINT "FK_f3f81867fa1bc0c9779810e33ea"`);
        await queryRunner.query(`ALTER TABLE "request_detail_adjustment" DROP CONSTRAINT "FK_8bf917615012117d7f04fd4cf9d"`);
        await queryRunner.query(`ALTER TABLE "request_detail_overtime" DROP CONSTRAINT "FK_bc21d1820c0393e0d6b9fde485d"`);
        await queryRunner.query(`ALTER TABLE "request_detail_time_off" DROP CONSTRAINT "FK_4cca4871b1f37d46e6c90671864"`);
        await queryRunner.query(`ALTER TABLE "attendance_daily_punches" DROP CONSTRAINT "FK_d2268f587719729593e28fc6936"`);
        await queryRunner.query(`ALTER TABLE "leave_policies" DROP CONSTRAINT "FK_e944bd0d894099fe5632364d219"`);
        await queryRunner.query(`ALTER TABLE "leave_policy_rules" DROP CONSTRAINT "FK_3b14a2e187e55b94c01d54223f6"`);
        await queryRunner.query(`ALTER TABLE "leave_policy_rules" DROP CONSTRAINT "FK_192cb2e4093ad9d4e9c4582dc4b"`);
        await queryRunner.query(`ALTER TABLE "leave_types" DROP CONSTRAINT "FK_dd27cdf2939bc23d54c5a76ffee"`);
        await queryRunner.query(`ALTER TABLE "attendance_methods" DROP CONSTRAINT "FK_7cf15dacc1770dcc50c9bf2a7d2"`);
        await queryRunner.query(`ALTER TABLE "employee_statuses" DROP CONSTRAINT "FK_a6574c554b6e0b7493570e464d2"`);
        await queryRunner.query(`ALTER TABLE "employee_types" DROP CONSTRAINT "FK_aac82752e7927d632704a21e61b"`);
        await queryRunner.query(`ALTER TABLE "job_levels" DROP CONSTRAINT "FK_eafba85d3dac4465dfb623edcc0"`);
        await queryRunner.query(`ALTER TABLE "attendance_groups" DROP CONSTRAINT "FK_1bdd8eb6d4a4964b55e959f3581"`);
        await queryRunner.query(`ALTER TABLE "attendance_groups" DROP CONSTRAINT "FK_496072134ffffe2a4bcc6fb1d9d"`);
        await queryRunner.query(`ALTER TABLE "shifts" DROP CONSTRAINT "FK_e155f8dd2a50f91604c8d946369"`);
        await queryRunner.query(`ALTER TABLE "shift_rest_rules" DROP CONSTRAINT "FK_2fed9c0812c54848b2cd7201c2e"`);
        await queryRunner.query(`ALTER TABLE "attendance_month_settings" DROP CONSTRAINT "FK_9c7dbd7a2b677fd4bccaf6e0dad"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b42531bfb853f20d06f1177653"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed390b2466f6f70591a7d93e0a"`);
        await queryRunner.query(`DROP TABLE "employee_departments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_641ddaa8aaa61c0a3bd554e3d7"`);
        await queryRunner.query(`DROP TABLE "timesheet_adjustment_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_edc5d3a356155c2fec8a3e5e33"`);
        await queryRunner.query(`DROP TABLE "work_locations"`);
        await queryRunner.query(`DROP TABLE "companies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92e489091fca8e3433a1f6042b"`);
        await queryRunner.query(`DROP TABLE "attendance_monthly_timesheets"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c689b7c9078088568fe841f3a4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a123f781aec89de6ee8ea17246"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed8bf314ae9f18006123e23566"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bcdf921072a19dd2758a628c5c"`);
        await queryRunner.query(`DROP TABLE "employees"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb9081146343629a3a34ecd1f4"`);
        await queryRunner.query(`DROP TABLE "departments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f52963827865bbefb1398e754f"`);
        await queryRunner.query(`DROP TABLE "attendance_punch_records"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91c8bfaa321bf2003b5d6856bf"`);
        await queryRunner.query(`DROP TABLE "attendance_daily_timesheets"`);
        await queryRunner.query(`DROP TABLE "attendance_requests"`);
        await queryRunner.query(`DROP TABLE "request_detail_adjustment"`);
        await queryRunner.query(`DROP TABLE "request_detail_overtime"`);
        await queryRunner.query(`DROP TABLE "request_detail_time_off"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7ca3649028e5eab9ca4ea5ea3"`);
        await queryRunner.query(`DROP TABLE "attendance_daily_punches"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89303fbcb2f5897d84f1ccec35"`);
        await queryRunner.query(`DROP TABLE "leave_policies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c58a23a2bf708464e268ca2415"`);
        await queryRunner.query(`DROP TABLE "leave_policy_rules"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_df83f49dd79df2a2c3f189fd8f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_600530eb1d9f853dd746e5819c"`);
        await queryRunner.query(`DROP TABLE "leave_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f7ab5fa6781fcf098de4a62e48"`);
        await queryRunner.query(`DROP TABLE "attendance_methods"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6cfec6890bce2fe8dfb9c08266"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b69943ca196ae982e02fa5ef98"`);
        await queryRunner.query(`DROP TABLE "employee_statuses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c39e1b9bddd039527213a68eb4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c2afe0e63d665bfb42e7c47e2"`);
        await queryRunner.query(`DROP TABLE "employee_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff4edf9c32127346169a68fcd9"`);
        await queryRunner.query(`DROP TABLE "job_levels"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_912027997643770c7363e28df9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e61dd1fab443e84f7576c7f2fa"`);
        await queryRunner.query(`DROP TABLE "attendance_groups"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_555c88b66687c3694b196c5b02"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a29e2a5f47594e13dec61b1deb"`);
        await queryRunner.query(`DROP TABLE "shifts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_156e6b1044f24a6c9192f9e93a"`);
        await queryRunner.query(`DROP TABLE "shift_rest_rules"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b065ef630ddc3e104f35f6c370"`);
        await queryRunner.query(`DROP TABLE "attendance_month_settings"`);
    }

}
