version: '3.8'

services:
  migration:
    image: timekeeping-migration:latest
    build:
      context: .
      target: builder
    container_name: timekeeping-migration
    env_file: 
      - .env
    command: yarn migration:run

  api-app:
    image: timekeeping-api:latest
    build:
      context: .
      target: runner
    container_name: timekeeping-api
    restart: always
    env_file: 
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    command: node dist/main
    depends_on:
      migration:
        condition: service_completed_successfully