//Loại điều chỉnh công ca
export enum AdjustmentReasonCode {
  BROKEN_MACHINE = 'BROKEN_MACHINE',
  POWER_OUTAGE = 'POWER_OUTAGE',
  NETWORK_LOSS = 'NETWORK_LOSS',
  NO_FINGERPRINT = 'NO_FINGERPRINT',
  NOT_LOCKED_FINGERPRINT = 'NOT_LOCKED_FINGERPRINT',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
}
